FROM maven:3.9.9-amazoncorretto-17-alpine  AS build
WORKDIR /home/app

COPY ./pom.xml /home/app/pom.xml
COPY ./src/main/java/gr/ariskatsarakis/organizer/OrganizerApplication.java /home/app/src/main/java/gr/ariskatsarakis/organizer/OrganizerApplication.java

RUN mvn clean install 

COPY . /home/app

CMD ["mvn","spring-boot:run"]
