spring.application.name=organizer
# logging
logging.level.root=info
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error


# database

spring.datasource.username=${POSTGRESDB_USER}
spring.datasource.password=${POSTGRESDB_ROOT_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${POSTGRESDB_URL}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
